name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*'  # 当推送标签（如 v1.0.0）时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 设置 Python 版本（你可以根据需要更改）

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install project dependencies
      run: |
        poetry install

    - name: Build the package
      run: |
        poetry build

    - name: Publish to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}  # 使用 GitHub Secrets 存储 PyPI API Token
      run: |
        poetry publish --build --repository pypi
